name: get-data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 */1 * * *" # trigger every hour
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run script
        run: |
          cd get-data
          mkdir out
          npm install
          npm run start

      - name: Deploy data files
        run: |
          git clone --branch gh-pages https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/juusolain/korona.git dist
          cp get-data/out/* dist/data/
          git config --global user.email "korona-graphs@juusolain.fi"
          git config --global user.name "Korona graphs bot"
          cd dist
          git add -A
          git commit -m "update"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/juusolain/korona.git gh-pages
